// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdimuC7JfnRLeRiVLm9FZWSpEp77gXl7Q',
    appId: '1:182349555558:web:e77f12452189a92104caa7',
    messagingSenderId: '182349555558',
    projectId: 'lostandfound-606de',
    authDomain: 'lostandfound-606de.firebaseapp.com',
    storageBucket: 'lostandfound-606de.firebasestorage.app',
    measurementId: 'G-B1RYRESWH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ65H5Pp05NXF2BN-ZSyJ7U4rSPZD5VTw',
    appId: '1:182349555558:android:66932ffea348858604caa7',
    messagingSenderId: '182349555558',
    projectId: 'lostandfound-606de',
    storageBucket: 'lostandfound-606de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWnTnAe_ai_C2Lg3ucPv7ExK7E5lavsc',
    appId: '1:182349555558:ios:e8b4cf50f1afaa4404caa7',
    messagingSenderId: '182349555558',
    projectId: 'lostandfound-606de',
    storageBucket: 'lostandfound-606de.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWnTnAe_ai_C2Lg3ucPv7ExK7E5lavsc',
    appId: '1:182349555558:ios:e8b4cf50f1afaa4404caa7',
    messagingSenderId: '182349555558',
    projectId: 'lostandfound-606de',
    storageBucket: 'lostandfound-606de.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdimuC7JfnRLeRiVLm9FZWSpEp77gXl7Q',
    appId: '1:182349555558:web:429e4cb8ea718e2a04caa7',
    messagingSenderId: '182349555558',
    projectId: 'lostandfound-606de',
    authDomain: 'lostandfound-606de.firebaseapp.com',
    storageBucket: 'lostandfound-606de.firebasestorage.app',
    measurementId: 'G-4G608GJF9N',
  );
}
